//! Tests for the parser v3 implementation (legacy, deprecated)
//! These tests are preserved for historical reference but are ignored
//! as the codebase has moved to parser v4 with GLR support.

mod common;

use adze::parser_v4::Parser;
use adze_glr_core::{Action, ParseRule, ParseTable};
use adze_ir::*;
use glr_test_support::make_minimal_table;

fn create_simple_arithmetic_grammar() -> Grammar {
    let mut grammar = Grammar {
        name: "arithmetic".to_string(),
        rules: indexmap::IndexMap::new(),
        tokens: indexmap::IndexMap::new(),
        precedences: vec![],
        conflicts: vec![],
        externals: vec![],
        extras: vec![],
        fields: indexmap::IndexMap::new(),
        supertypes: vec![],
        inline_rules: vec![],
        alias_sequences: indexmap::IndexMap::new(),
        production_ids: indexmap::IndexMap::new(),
        rule_names: indexmap::IndexMap::new(),
        max_alias_sequence_length: 0,
        symbol_registry: None,
        word_token: None,
        lexical_metadata: indexmap::IndexMap::new(),
    };

    // Define symbol IDs
    let _eof_id = SymbolId(0);
    let num_id = SymbolId(1);
    let plus_id = SymbolId(2);
    let expr_id = SymbolId(3);

    // Add tokens
    grammar.tokens.insert(
        num_id,
        Token {
            name: "number".to_string(),
            pattern: TokenPattern::Regex(r"\d+".to_string()),
            fragile: false,
        },
    );

    grammar.tokens.insert(
        plus_id,
        Token {
            name: "plus".to_string(),
            pattern: TokenPattern::String("+".to_string()),
            fragile: false,
        },
    );

    // Add rules
    // Rule 0: expr -> number
    let rule0 = Rule {
        lhs: expr_id,
        rhs: vec![Symbol::Terminal(num_id)],
        precedence: None,
        associativity: None,
        fields: vec![],
        production_id: ProductionId(0),
    };

    // Rule 1: expr -> expr + expr
    let rule1 = Rule {
        lhs: expr_id,
        rhs: vec![
            Symbol::NonTerminal(expr_id),
            Symbol::Terminal(plus_id),
            Symbol::NonTerminal(expr_id),
        ],
        precedence: Some(PrecedenceKind::Static(1)),
        associativity: Some(Associativity::Left),
        fields: vec![],
        production_id: ProductionId(1),
    };

    grammar.rules.entry(expr_id).or_default().push(rule0);
    grammar.rules.entry(expr_id).or_default().push(rule1);

    grammar.production_ids.insert(RuleId(0), ProductionId(0));
    grammar.production_ids.insert(RuleId(1), ProductionId(1));

    grammar
}

fn create_simple_parse_table() -> ParseTable {
    // This is a simplified parse table for testing
    // In reality, this would be generated by the GLR table generator

    // State 0: Initial state
    // - number -> shift to state 1
    // - expr -> goto state 2

    // State 1: After seeing number
    // - * -> reduce by rule 0 (expr -> number)

    // State 2: After seeing expr
    // - + -> shift to state 3
    // - EOF -> accept

    // State 3: After seeing expr +
    // - number -> shift to state 4
    // - expr -> goto state 5

    // State 4: After seeing number (in expr + context)
    // - * -> reduce by rule 0 (expr -> number)

    // State 5: After seeing expr + expr
    // - * -> reduce by rule 1 (expr -> expr + expr)

    let mut action_table: Vec<Vec<Vec<Action>>> = vec![vec![vec![Action::Error]; 4]; 6];
    let mut goto_table = vec![vec![StateId(0); 4]; 6];

    // State 0
    action_table[0][1] = vec![Action::Shift(StateId(1))]; // number
    goto_table[0][3] = StateId(2); // expr

    // State 1
    action_table[1][0] = vec![Action::Reduce(RuleId(0))]; // EOF
    action_table[1][1] = vec![Action::Reduce(RuleId(0))]; // number
    action_table[1][2] = vec![Action::Reduce(RuleId(0))]; // +

    // State 2
    action_table[2][0] = vec![Action::Accept]; // EOF
    action_table[2][2] = vec![Action::Shift(StateId(3))]; // +

    // State 3
    action_table[3][1] = vec![Action::Shift(StateId(4))]; // number
    goto_table[3][3] = StateId(5); // expr

    // State 4
    action_table[4][0] = vec![Action::Reduce(RuleId(0))]; // EOF
    action_table[4][1] = vec![Action::Reduce(RuleId(0))]; // number
    action_table[4][2] = vec![Action::Reduce(RuleId(0))]; // +

    // State 5
    action_table[5][0] = vec![Action::Reduce(RuleId(1))]; // EOF
    action_table[5][1] = vec![Action::Reduce(RuleId(1))]; // number
    action_table[5][2] = vec![Action::Reduce(RuleId(1))]; // +

    // Create parse rules for the table
    let rules = vec![
        ParseRule {
            lhs: SymbolId(3), // expr
            rhs_len: 1,       // expr -> number
        },
        ParseRule {
            lhs: SymbolId(3), // expr
            rhs_len: 3,       // expr -> expr + expr
        },
    ];

    make_minimal_table(
        action_table,
        goto_table,
        rules,
        SymbolId(3), // start_symbol (expr)
        SymbolId(0), // eof_symbol
        0,           // external_token_count
    )
}

#[test]
#[ignore = "TODO: Update for parser_v4"]
fn test_parse_number() {
    let grammar = create_simple_arithmetic_grammar();
    let parse_table = create_simple_parse_table();

    let mut parser = Parser::new(grammar, parse_table, "test".to_string());

    match parser.parse_tree("42") {
        Ok(root) => {
            assert_eq!(root.symbol.0, 3); // expr
        }
        Err(e) => panic!("Parse failed: {}", e),
    }
}

#[test]
#[ignore = "TODO: Update for parser_v4"]
fn test_parse_addition() {
    let grammar = create_simple_arithmetic_grammar();
    let parse_table = create_simple_parse_table();

    let mut parser = Parser::new(grammar, parse_table, "test".to_string());

    match parser.parse_tree("1+2") {
        Ok(root) => {
            assert_eq!(root.symbol.0, 3); // expr
        }
        Err(e) => panic!("Parse failed: {}", e),
    }
}

#[test]
#[ignore = "TODO: Update for parser_v4"]
fn test_parse_with_whitespace() {
    let grammar = create_simple_arithmetic_grammar();
    let parse_table = create_simple_parse_table();

    let mut parser = Parser::new(grammar, parse_table, "test".to_string());

    // The lexer should skip whitespace
    match parser.parse_tree("1 + 2") {
        Ok(root) => {
            assert_eq!(root.symbol.0, 3); // expr
        }
        Err(e) => panic!("Parse failed: {}", e),
    }
}
