//! Convert Tree-sitter JSON format to GrammarJs structure
//!
//! This module handles the conversion from the JSON format generated by
//! adze's generate_grammars to the GrammarJs intermediate format.

use super::{ExternalToken, GrammarJs, Rule};
use crate::grammar_js::infer_imported_compiler_identity;
use anyhow::{Context, Result};
use serde_json::Value;

/// Convert Tree-sitter JSON format to GrammarJs
pub fn from_tree_sitter_json(value: &Value) -> Result<GrammarJs> {
    let obj = value
        .as_object()
        .context("Expected JSON object for grammar")?;

    let name = obj
        .get("name")
        .and_then(|v| v.as_str())
        .context("Grammar missing 'name' field")?
        .to_string();

    let mut grammar_js = GrammarJs::new(name);

    // Parse word token
    if let Some(word) = obj.get("word")
        && let Some(word_str) = word.as_str()
    {
        grammar_js.word = Some(word_str.to_string());
    }

    // Parse inline rules
    if let Some(inline) = obj.get("inline")
        && let Some(inline_arr) = inline.as_array()
    {
        for item in inline_arr {
            if let Some(s) = item.as_str() {
                grammar_js.inline.push(s.to_string());
            }
        }
    }

    // Parse conflicts
    if let Some(conflicts) = obj.get("conflicts")
        && let Some(conflicts_arr) = conflicts.as_array()
    {
        for conflict_set in conflicts_arr {
            if let Some(set_arr) = conflict_set.as_array() {
                let mut conflict_rules = Vec::new();
                for rule in set_arr {
                    if let Some(s) = rule.as_str() {
                        conflict_rules.push(s.to_string());
                    }
                }
                grammar_js.conflicts.push(conflict_rules);
            }
        }
    }

    // Parse extras
    if let Some(extras) = obj.get("extras")
        && let Some(extras_arr) = extras.as_array()
    {
        for extra in extras_arr {
            if let Ok(rule) = parse_rule(extra) {
                grammar_js.extras.push(rule);
            }
        }
    }

    // Parse externals
    if let Some(externals) = obj.get("externals")
        && let Some(externals_arr) = externals.as_array()
    {
        for (i, external) in externals_arr.iter().enumerate() {
            if let Some(external_obj) = external.as_object() {
                if let Some(name) = external_obj.get("name").and_then(|v| v.as_str()) {
                    grammar_js.externals.push(ExternalToken {
                        name: name.to_string(),
                        symbol: format!("external_{}", i),
                    });
                }
            } else if let Some(name) = external.get("name").and_then(|v| v.as_str()) {
                grammar_js.externals.push(ExternalToken {
                    name: name.to_string(),
                    symbol: format!("external_{}", i),
                });
            }
        }
    }

    // Parse supertypes
    if let Some(supertypes) = obj.get("supertypes")
        && let Some(supertypes_arr) = supertypes.as_array()
    {
        for supertype in supertypes_arr {
            if let Some(s) = supertype.as_str() {
                grammar_js.supertypes.push(s.to_string());
            }
        }
    }

    // Parse rules
    if let Some(rules) = obj.get("rules")
        && let Some(rules_obj) = rules.as_object()
    {
        for (rule_name, rule_value) in rules_obj {
            if let Ok(rule) = parse_rule(rule_value) {
                grammar_js.rules.insert(rule_name.clone(), rule);
            }
        }
    }

    if let Some(start_symbol) = obj.get("start_symbol").and_then(|v| v.as_str()) {
        grammar_js.start_symbol = Some(start_symbol.to_string());
    }

    if let Some(relations) = obj.get("wrapper_token_relations") {
        if let Some(relations_obj) = relations.as_object() {
            for (wrapper, token) in relations_obj {
                if let Some(token_name) = token.as_str() {
                    grammar_js
                        .wrapper_token_relations
                        .insert(wrapper.clone(), token_name.to_string());
                }
            }
        } else if let Some(relations_arr) = relations.as_array() {
            for entry in relations_arr {
                if let Some(entry_obj) = entry.as_object() {
                    let wrapper = entry_obj
                        .get("wrapper")
                        .and_then(|v| v.as_str())
                        .context("wrapper_token_relations entry missing 'wrapper'")?;
                    let token = entry_obj
                        .get("token")
                        .and_then(|v| v.as_str())
                        .context("wrapper_token_relations entry missing 'token'")?;
                    grammar_js
                        .wrapper_token_relations
                        .insert(wrapper.to_string(), token.to_string());
                }
            }
        }
    }

    infer_imported_compiler_identity(&mut grammar_js);

    Ok(grammar_js)
}

/// Parse a rule from JSON
fn parse_rule(value: &Value) -> Result<Rule> {
    let obj = value.as_object().context("Expected object for rule")?;

    let rule_type = obj
        .get("type")
        .and_then(|v| v.as_str())
        .context("Rule missing 'type' field")?;

    match rule_type {
        "STRING" => {
            let value = obj
                .get("value")
                .and_then(|v| v.as_str())
                .context("STRING rule missing 'value'")?;
            Ok(Rule::String {
                value: value.to_string(),
            })
        }

        "PATTERN" => {
            let value = obj
                .get("value")
                .and_then(|v| v.as_str())
                .context("PATTERN rule missing 'value'")?;
            Ok(Rule::Pattern {
                value: value.to_string(),
            })
        }

        "SYMBOL" => {
            let name = obj
                .get("name")
                .and_then(|v| v.as_str())
                .context("SYMBOL rule missing 'name'")?;
            Ok(Rule::Symbol {
                name: name.to_string(),
            })
        }

        "BLANK" => Ok(Rule::Blank),

        "SEQ" => {
            let members_arr = obj
                .get("members")
                .and_then(|v| v.as_array())
                .context("SEQ rule missing 'members'")?;
            let mut members = Vec::new();
            for member in members_arr {
                members.push(parse_rule(member)?);
            }
            Ok(Rule::Seq { members })
        }

        "CHOICE" => {
            let members_arr = obj
                .get("members")
                .and_then(|v| v.as_array())
                .context("CHOICE rule missing 'members'")?;
            let mut members = Vec::new();
            for member in members_arr {
                members.push(parse_rule(member)?);
            }
            Ok(Rule::Choice { members })
        }

        "REPEAT" => {
            let content = obj
                .get("content")
                .context("REPEAT rule missing 'content'")?;
            Ok(Rule::Repeat {
                content: Box::new(parse_rule(content)?),
            })
        }

        "REPEAT1" => {
            let content = obj
                .get("content")
                .context("REPEAT1 rule missing 'content'")?;
            Ok(Rule::Repeat1 {
                content: Box::new(parse_rule(content)?),
            })
        }

        "OPTIONAL" => {
            let value = obj
                .get("value")
                .or_else(|| obj.get("content"))
                .context("OPTIONAL rule missing 'value' or 'content'")?;
            Ok(Rule::Optional {
                value: Box::new(parse_rule(value)?),
            })
        }

        "PREC" => {
            let value = obj
                .get("value")
                .and_then(|v| v.as_i64())
                .context("PREC rule missing 'value'")?;
            let content = obj.get("content").context("PREC rule missing 'content'")?;
            Ok(Rule::Prec {
                value: value as i32,
                content: Box::new(parse_rule(content)?),
            })
        }

        "PREC_LEFT" => {
            let value = obj
                .get("value")
                .and_then(|v| v.as_i64())
                .context("PREC_LEFT rule missing 'value'")?;
            let content = obj
                .get("content")
                .context("PREC_LEFT rule missing 'content'")?;
            Ok(Rule::PrecLeft {
                value: value as i32,
                content: Box::new(parse_rule(content)?),
            })
        }

        "PREC_RIGHT" => {
            let value = obj
                .get("value")
                .and_then(|v| v.as_i64())
                .context("PREC_RIGHT rule missing 'value'")?;
            let content = obj
                .get("content")
                .context("PREC_RIGHT rule missing 'content'")?;
            Ok(Rule::PrecRight {
                value: value as i32,
                content: Box::new(parse_rule(content)?),
            })
        }

        "PREC_DYNAMIC" => {
            let value = obj
                .get("value")
                .and_then(|v| v.as_i64())
                .context("PREC_DYNAMIC rule missing 'value'")?;
            let content = obj
                .get("content")
                .context("PREC_DYNAMIC rule missing 'content'")?;
            Ok(Rule::PrecDynamic {
                value: value as i32,
                content: Box::new(parse_rule(content)?),
            })
        }

        "TOKEN" => {
            let content = obj.get("content").context("TOKEN rule missing 'content'")?;
            Ok(Rule::Token {
                content: Box::new(parse_rule(content)?),
            })
        }

        "IMMEDIATE_TOKEN" => {
            let content = obj
                .get("content")
                .context("IMMEDIATE_TOKEN rule missing 'content'")?;
            Ok(Rule::ImmediateToken {
                content: Box::new(parse_rule(content)?),
            })
        }

        "FIELD" => {
            let name = obj
                .get("name")
                .and_then(|v| v.as_str())
                .context("FIELD rule missing 'name'")?;
            let content = obj.get("content").context("FIELD rule missing 'content'")?;
            Ok(Rule::Field {
                name: name.to_string(),
                content: Box::new(parse_rule(content)?),
            })
        }

        "ALIAS" => {
            let value = obj
                .get("value")
                .and_then(|v| v.as_str())
                .context("ALIAS rule missing 'value'")?;
            let named = obj.get("named").and_then(|v| v.as_bool()).unwrap_or(false);
            let content = obj.get("content").context("ALIAS rule missing 'content'")?;
            Ok(Rule::Alias {
                content: Box::new(parse_rule(content)?),
                value: value.to_string(),
                named,
            })
        }

        _ => {
            anyhow::bail!("Unknown rule type: {}", rule_type)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn test_simple_grammar_conversion() {
        let json = json!({
            "name": "test",
            "word": "identifier",
            "rules": {
                "source_file": {
                    "type": "SYMBOL",
                    "name": "expression"
                },
                "expression": {
                    "type": "CHOICE",
                    "members": [
                        {
                            "type": "SYMBOL",
                            "name": "number"
                        },
                        {
                            "type": "SYMBOL",
                            "name": "identifier"
                        }
                    ]
                },
                "number": {
                    "type": "PATTERN",
                    "value": "\\d+"
                },
                "identifier": {
                    "type": "PATTERN",
                    "value": "[a-zA-Z_]\\w*"
                }
            },
            "extras": [
                {
                    "type": "PATTERN",
                    "value": "\\s"
                }
            ]
        });

        let grammar_js = from_tree_sitter_json(&json).unwrap();
        assert_eq!(grammar_js.name, "test");
        assert_eq!(grammar_js.word, Some("identifier".to_string()));
        assert_eq!(grammar_js.rules.len(), 4);
        assert_eq!(grammar_js.extras.len(), 1);
    }
}
