#!/usr/bin/env bash
# release-graph-crates.sh — Print ledger-selected release crate order.
#
# Authority: policy/release-graph.toml (see `cargo xtask check-release-graph`).
# Derived list: scripts/release-crates.txt (regenerated by generate-release-graph).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$ROOT_DIR"
cargo run -q -p xtask -- print-release-graph
