//! Typed AST provenance value types.

use super::*;

/// A typed AST value paired with document-level syntax provenance.
///
/// The provenance describes the selected document syntax used as the extraction
/// root. It is intentionally coarser than per-AST-node provenance, which needs
/// a separate contract because semantic AST values may combine, omit, or
/// synthesize concrete syntax.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TypedAst<T> {
    pub(in crate::document) value: T,
    pub(in crate::document) provenance: Provenance,
}

impl<T> TypedAst<T> {
    /// Return the extracted typed AST value.
    pub fn value(&self) -> &T {
        &self.value
    }

    /// Return document-level syntax provenance for this typed AST.
    pub fn provenance(&self) -> &Provenance {
        &self.provenance
    }

    /// Consume this wrapper and return the typed AST value.
    pub fn into_value(self) -> T {
        self.value
    }

    /// Consume this wrapper and return both value and provenance.
    pub fn into_parts(self) -> (T, Provenance) {
        (self.value, self.provenance)
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub(in crate::document) struct TypedAstExtractionTarget {
    pub(in crate::document) child_index: Option<usize>,
    pub(in crate::document) provenance: Provenance,
}

/// Syntax provenance for a typed AST projection.
///
/// The alpha implementation currently records [`Provenance::Node`] for the
/// extraction root. The other variants define the intended shape for future
/// semantic AST values that are span-based, combine multiple syntax nodes, or
/// are synthesized from recovery/defaulting.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Provenance {
    /// The value came from one document-local node.
    Node(NodeId),
    /// The value came from a source byte span without a single owning node.
    Span(Range<usize>),
    /// The value came from multiple document-local nodes.
    Nodes(Vec<NodeId>),
    /// The value was synthesized by extraction or recovery.
    Synthetic {
        /// Source byte span associated with the synthetic value.
        span: Range<usize>,
        /// Reason the value was synthesized.
        reason: SyntheticReason,
    },
}

/// Reason a provenance entry was synthesized.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum SyntheticReason {
    /// Parser recovery supplied missing syntax.
    MissingSyntax,
    /// Typed extraction supplied a default value.
    ExtractionDefault,
    /// The value was generated by a parser or runtime fallback.
    RuntimeFallback,
}
